### ISSUE TITLE
json editor not building - compiling  (OSOE-772)

### ISSUE THREAD

**Issue by giannik** [Lombiq/Orchard-JSON-Editor#56]
cannot  compile because of unknown class   **ResourceManagerContentSecurityPolicyProvider**  here :

https://github.com/Lombiq/Orchard-JSON-Editor/blob/1bad5734e38384b67d2792d542029aa253c0553f/Lombiq.JsonEditor/Services/JsonEditorContentSecurityPolicyProvider.cs#L17

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-772)

**Comment by giannik** [comment]
sorry my mistake. it works

**Comment by Piedone** [comment]
Great then!
